#pragma config(StandardModel, "Autobot IQ")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Yksinkertaisin mahdolllinen arcade control ohjelma. Talla ohjelmalla robotti jai joskus
// liikkumaan hiljaa, vaikka ohjaussauvat loysattiin.
// Tasta paastaan helposti eroon siten etta jos getJoystickValue:n antama lukema on lahella
// nollaa, niin laitetaan setMotorSpeed-funktiolla moottorin nopeus nollaksi.
// Tama korjaus on tehty ohjelman seuraavaan versioon.
// (Tamantyyppinen ratkaisu on tehty myos natural language funktiossa arcadecontrol.)


task main()
{
	setMotorBrakeMode(leftMotor, motorCoast);     // Robottia on helpompi siirreella lykkaamalla
	setMotorBrakeMode(rightMotor, motorCoast);    // talla asetuksella


	while(true)
	{

		setMotorSpeed(leftMotor,  (getJoystickValue(ChA) + getJoystickValue(ChC))/2);  	// (y - x)/2
		setMotorSpeed(rightMotor, (getJoystickValue(ChA) - getJoystickValue(ChC))/2);  	// (y + x)/2
	}
}
