#pragma config(StandardModel, "Autobot IQ")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Olli Pulkkinen 12.4.2016

// Jos getJoystickValue:n antamista arvoista kumpikaan ei eroa nollasta PYSAYTYSRAJAa enempaa, niin asetetaan
// moottorit seis. Tama siksi etta joskus robotti jai liikkumaan (ensimmaisessa ohjelmaversiossa) vaikka
// ohjaussauvat loysattiin. Tamantyyppinen ratkaisu on tehty myos natural language funktiossa arcadecontrol.

#define PYSAYTYSRAJA 10     // Teksti PYSAYTYSRAJA korvautuu sen jalkeisella tekstilla koodissa.


// Jos halutaan kahden sauvan ohjaus(vasemmalla ohjataan eteen/taakse oikealla kaannellan), niin otetaan
// kayttoon seuraavat kaksi rivia:

#define KANAVAETEENJATAAKSE ChA

#define KANAVAOIKEALLEJAVASEMMALLE ChC


// Jos halutaan pelkastaan oikean sauvan ohjaus, niin otetaan kayttoon seuraavat kaksi rivia:

// #define KANAVAETEENJATAAKSE ChD

// #define KANAVAOIKEALLEJAVASEMMALLE ChC


// Jos halutaan pelkastaan vasemman sauvan ohjaus, niin otetaan kayttoon seuraavat kaksi rivia:

// #define KANAVAETEENJATAAKSE ChA

// #define KANAVAOIKEALLEJAVASEMMALLE ChB



// Jos jostain syysta haluttaisiin viela kahden sauvan ohjaus, jossa oikealla sauvalla ajetaan eteen/taakse ja
// vasemmalla kaannellaan, niin se onnistuu ottamalla kaksi seuraavaa rivia kayttoon:

// #define KANAVAETEENJATAAKSE ChD

// #define KANAVAOIKEALLEJAVASEMMALLE ChB


task main()
{

  setMotorBrakeMode(leftMotor, motorCoast);     // Robottia on helpompi siirreella lykkaamalla
  setMotorBrakeMode(rightMotor, motorCoast);    // talla asetuksella


	while(true)     // Ikuinen silmukka
	{

	  // Jos vahintaan toinen getJoystickValue-arvoista on PYSAYTYSRAJAa suurempi
	  // niin talloin robotin moottoreille annetaan nopeudet normaalin arcade control -ohjauksen mukaisesti.

	  if(abs(getJoystickValue(KANAVAETEENJATAAKSE)) > PYSAYTYSRAJA || abs(getJoystickValue(KANAVAOIKEALLEJAVASEMMALLE)) > PYSAYTYSRAJA){

			setMotorSpeed(leftMotor,  (getJoystickValue(KANAVAETEENJATAAKSE) + getJoystickValue(KANAVAOIKEALLEJAVASEMMALLE))/2); // (y + x)/2
																																										                                       // Nama ovat aina valilla -100...100
			setMotorSpeed(rightMotor, (getJoystickValue(KANAVAETEENJATAAKSE) - getJoystickValue(KANAVAOIKEALLEJAVASEMMALLE))/2); // (y - x)/2

		}else{

			setMotorSpeed(leftMotor, 0);    // Jos kumpikaan getJoystickValue-arvoista ei ole itseisarvoltaan pysaytysrajaa
																			// suurempi niin pysaytetaan.
			setMotorSpeed(rightMotor, 0);

		}

	}

}
