#pragma config(StandardModel, "Autobot IQ")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


// Olli Pulkkinen 15.4.2016


// Tama ohjelma vaihtelee ledin vareja pikku hiljaa ajan kuluessa.
// Samalla voidaan koko ajan ajaa robotilla.
// Huom. Varien arvot ledille valilla 0-255, 12750 = 255*50

#define PYSAYTYSRAJA 10     // nimetty vakio jota kaytetaan paivitaMoottorit-funktiossa.


void paivitaMoottorit(void);  // Main-funktiossa kaytettavan funktion prototyyppi.


task main()
{

  short red, green, blue;


	setMotorBrakeMode(leftMotor, motorCoast);     // Robottia on helpompi siirreella lykkaamalla
	setMotorBrakeMode(rightMotor, motorCoast);    // talla asetuksella



	// Seuraava ohjelma pyörittelee läpi erilaisia värejä.

	while (true) {                   // Ikuinen silmukka

	  clearTimer(T1);

	  blue = 0;

		while (time1[T1] <= 12750) {   // Tassa silmukassa pyoritaan siis 12,75 s.

		  paivitaMoottorit();

      red = 255-time1[T1]/50;      // Punaisen maara pienenee koko ajan

      green = time1[T1]/50;        // Vihrean maara kasvaa koko ajan

			setTouchLEDRGB(touchLED, red, green, blue);

		}

		clearTimer(T1);

		red = 0;

		while (time1[T1] <= 12750) {    // Tassa silmukassa pyoritaan siis 12,75 s.

			paivitaMoottorit();

			green = 255-time1[T1]/50;     // Vihrean maara pienenee koko ajan

      blue = time1[T1]/50;					// Sinisen maara kasvaa koko ajan

			setTouchLEDRGB(touchLED, red, green, blue);
		}

		clearTimer(T1);

		green = 0;

		while (time1[T1] <= 12750) {    // Tassa silmukassa pyoritaan siis 12,75 s.

			paivitaMoottorit();

			blue = 255-time1[T1]/50;      // Sinisen maara pienenee koko ajan

			red = time1[T1]/50;           // Punaisen maara kasvaa koko ajan

			setTouchLEDRGB(touchLED, red, green, blue);
		}

	}
}



// paivitaMoottorit-funktiossa luetaan Joystickien arvot ja asetetaan moottoreille vastaavat nopeudet.
// Main-funktiosta saadaan lyhyempi ja helpommin hahmotettava kun toistuvista koodiosioista
// kirjoitetaan oma funktio.

void paivitaMoottorit(void){

	short kanavanALukema, kanavanCLukema, itseisarvoA, itseisarvoC;

	kanavanALukema = getJoystickValue(ChA);

	kanavanCLukema = getJoystickValue(ChC);

	itseisarvoA = abs(kanavanALukema);

	itseisarvoC = abs(kanavanCLukema);


	if(itseisarvoA > PYSAYTYSRAJA || itseisarvoC > PYSAYTYSRAJA){

		setMotorSpeed(leftMotor,  (kanavanALukema + kanavanCLukema)/2);  	// (y + x)/2

		setMotorSpeed(rightMotor, (kanavanALukema - kanavanCLukema)/2);  	// (y - x)/2

	}else{

		setMotorSpeed(leftMotor, 0);    // Jos kumpikaan ChA tai ChC arvosta ei ole itseisarvoltaan pysaytysrajaa suurempi
																		// niin pysaytetaan.
		setMotorSpeed(rightMotor, 0);
	}

}
