#pragma config(StandardModel, "Autobot IQ")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Olli Pulkkinen 12.4.2016

// Jos getJoystickValue:n antamista arvoista kumpikaan ei eroa nollasta PYSAYTYSRAJAa enempaa, niin asetetaan
// moottorit seis. Tama siksi etta joskus robotti jai liikkumaan (ensimmaisessa ohjelmaversiossa) vaikka
// ohjaussauvat loysattiin. Tamantyyppinen ratkaisu on tehty myos ainakin natural language funktiossa arcadecontrol.
// Myos natural languagen tankcontrol funktiossa on myos jokin taman tyyppinen ratkaisu.

#define PYSAYTYSRAJA 10     // Teksti PYSAYTYSRAJA korvautuu sen jalkeisella tekstilla koodissa.
                            // Voi olla etta tahan pitaa muuttaa esim. arvo 15, riippuu ohjaimesta ja sen kalibroinnista

// OIKEAKANAVA korvautuu koodissa tekstilla ChD ja VASENKANAVA tekstilla ChA.

#define OIKEAKANAVA ChD

#define VASENKANAVA ChA


task main()
{

  setMotorBrakeMode(leftMotor, motorCoast);     // Robottia on helpompi siirreella lykkaamalla
  setMotorBrakeMode(rightMotor, motorCoast);    // talla asetuksella


	while(true)     // Ikuinen silmukka
	{

	  // Jos vahintaan toinen getJoystickValue-arvoista on PYSAYTYSRAJAa suurempi
	  // niin talloin robotin moottoreille annetaan nopeudet normaalin tankdrive -ohjauksen mukaisesti.

	  if(abs(getJoystickValue(VASENKANAVA)) > PYSAYTYSRAJA || abs(getJoystickValue(OIKEAKANAVA)) > PYSAYTYSRAJA){

			setMotorSpeed(leftMotor,  (getJoystickValue(VASENKANAVA)));
																																										                                       // Nama ovat aina valilla -100...100
			setMotorSpeed(rightMotor, (getJoystickValue(OIKEAKANAVA)));

		}else{

			setMotorSpeed(leftMotor, 0);    // Jos kumpikaan getJoystickValue-arvoista ei ole itseisarvoltaan pysaytysrajaa
																			// suurempi niin pysaytetaan.
			setMotorSpeed(rightMotor, 0);

		}

	}

}
