#pragma config(StandardModel, "Autobot IQ")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


// Olli Pulkkinen 10.4.2016

// Yksinkeratainen tank drive ohjelma E ja F painonapeilla. Jos BtnEUp on pohjassa, niin vasen puoli
// vetaa eteenpain ja jos BtnEDown on pohjassa, niin vasen puoli vetaa taaksepain. Vastaavasti jos
// Jos BtnFUp on pohjassa, niin oikea puoli vetaa eteenpain ja jos BtnFDown on pohjassa, niin oikea puoli
// vetaa taaksepain. Lisaksi jos esim. seka BtnEUp ja BtnEDown ovat pohjassa, niin robotin vasen puoli vetaa eteenpain.
// Vastaavasti jos seka BtnFUp ja BtnFDown ovat pohjassa, niin robotin oikea puoli vetaa eteenpain.


#define NOPEUS 50 // Jokin luku valilta 0 <=...<= 100.
                  // Nyt asetettu 50, eli moottorit pyorivat puolella teholla.
task main()
{

	while(true)
	{

	  if(getJoystickValue(BtnEUp) == 1)

      setMotorSpeed(leftMotor,  NOPEUS);

    else if(getJoystickValue(BtnEDown) == 1)

	    setMotorSpeed(leftMotor,  -1*NOPEUS);

	  else

	    setMotorSpeed(leftMotor,  0);



	  if(getJoystickValue(BtnFUp) == 1)

      setMotorSpeed(rightMotor,  NOPEUS);

    else if(getJoystickValue(BtnFDown) == 1)

	    setMotorSpeed(rightMotor,  -1*NOPEUS);

	  else

	    setMotorSpeed(rightMotor,  0);

	}
}
